version: '3.8'

services:
  api:
    build: .
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/guardianx_db?schema=public
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=guardianx_production_secret_2026_jwt
      - AES_SECRET=guardianx_aes_256_key_32bytes!!
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: guardianx_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
